### ISSUE TITLE
Failed to run on macOSX

### ISSUE THREAD

**Issue by zchrissirhcz** [dargonfyl/imgui-painter#1]
Hi, dragonfyl

Thanks for sharing this GUI software source code.  

I build it on macOSX, the compile and link both ok, but failed to run, with error message:
```
(base) ➜  build git:(master) ./main
Shader::constructor:
Shader program:
ERROR: Compiled vertex shader was corrupt.
ERROR: Compiled fragment shader was corrupt.
```

macOSX system: 12.0.1
CPU: Intel

**Comment by dargonfyl** [comment]
Hi zchrissirhcz,

There is a hard-coded path right now for the shader paths because there were shader path problems with both XCode and Visual Studio. This is a personal project, so having it work on other systems was not a priority. If I have time, I will investigate the issue, but due to my current circumstances, that may be a while from now.

**Comment by zchrissirhcz** [comment]
Thanks for reply! I managed to find the hard coded paths and now success to open the GUI.
Anyway, thanks for sharing!
